## YAML Template.
---
# src/Blogger/BlogBundle/Resources/config/config.yml
parameters:
    # dirección de correo electrónico para contacto del Blogger
    blogger_blog.emails.contact_email: patrickbateman991@gmail.com