# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_homepage:
    path:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        methods:  GET
        
BloggerBlogBundle_about:
    path:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        methods:  GET
        
BloggerBlogBundle_contact:
    path:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        methods:  GET|POST
        
BloggerBlogBundle_blog_show:
    path:  /{id}/{slug}
    defaults: { _controller: BloggerBlogBundle:Blog:show, slug: default_slug }
    requirements:
        methods:  GET
        id: \d+
        
BloggerBlogBundle_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _methods:  POST
        blog_id: \d+ 
        
BloggerBlogBundle_post:
    path:  /post
    defaults: { _controller: BloggerBlogBundle:Post:new }
    requirements:
        _methods:  GET            
      
BloggerBlogBundle_create_post:
  path:  /create_post/
  defaults: { _controller: BloggerBlogBundle:Post:create_post }
  requirements:
      _methods:  GET|POST
      picture_id: \d+   
      
BloggerBlogBundle_upload_image:
  path:  /upload_image/{blog_id}
  defaults: { _controller: BloggerBlogBundle:Post:upload_image }
  requirements:
      _methods:  POST  
      
BloggerBlogBundle_edit_post:
    path:  /edit_post/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Post:edit_post }
    requirements:
        _methods:  GET|POST
        
BloggerBlogBundle_edit_image_show:
  path:  /edit_image_show/{blog_id}
  defaults: { _controller: BloggerBlogBundle:Post:edit_image_show }
  requirements:
      _methods:  GET
      
BloggerBlogBundle_edit_image:
  path:  /edit_image/{blog_id}
  defaults: { _controller: BloggerBlogBundle:Post:edit_image }
  requirements:
      _methods:  POST       